def break_rev(cipher_text):
    plain_text = cipher_text[::-1]
    return plain_text


if __name__ == '__main__':
    cipher_text_input = input("Enter cipher generated by reverse cipher: ")
    print("Here is the plain text:", break_rev(cipher_text_input))
